# Generated by Django 4.2.10 on 2026-06-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "estado",
            },
        ),
        migrations.CreateModel(
            name="Sugerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sugerencias",
                        to="sugerencias.estado",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugerencias",
                        to="products.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugerencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugerencia",
                "verbose_name_plural": "Sugerencias",
                "db_table": "sugerencia",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackSugerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fue_util", models.BooleanField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "sugerencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="sugerencias.sugerencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Sugerencia",
                "verbose_name_plural": "Feedbacks Sugerencia",
                "db_table": "feedback_sugerencia",
                "ordering": ["-fecha"],
            },
        ),
    ]
