# Generated by Django 4.2.10 on 2026-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_barra",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Código de barras (EAN-13)",
            ),
        ),
    ]
