# Generated by Django 4.2.10 on 2026-04-27 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supermarkets", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "second_unit_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="promotions/"),
                ),
                ("terms", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Promoción",
                "verbose_name_plural": "Promociones",
                "db_table": "promotions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PromotionType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("percentage", "Descuento porcentual"),
                            ("fixed_amount", "Descuento monto fijo"),
                            ("2x1", "2x1"),
                            ("3x2", "3x2"),
                            ("second_unit", "Segunda unidad con descuento"),
                            ("bank", "Promoción bancaria / medio de pago"),
                            ("day_of_week", "Promoción por día"),
                            ("category", "Promoción por categoría"),
                            ("product", "Promoción por producto"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de Promoción",
                "db_table": "promotion_types",
            },
        ),
        migrations.CreateModel(
            name="PromotionPaymentMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "Amex"),
                            ("debit", "Débito"),
                            ("mercado_pago", "Mercado Pago"),
                            ("naranja", "Naranja"),
                        ],
                        max_length=30,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_payment_methods",
            },
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotions",
                to="promotions.promotiontype",
            ),
        ),
        migrations.CreateModel(
            name="PromotionSupermarket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_supermarkets",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="supermarkets.supermarketchain",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_supermarkets",
                "unique_together": {("promotion", "supermarket")},
            },
        ),
        migrations.CreateModel(
            name="PromotionProduct",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="products.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_products",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_products",
                "unique_together": {("promotion", "product")},
            },
        ),
        migrations.CreateModel(
            name="PromotionDayOfWeek",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days_of_week",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_days_of_week",
                "unique_together": {("promotion", "weekday")},
            },
        ),
        migrations.CreateModel(
            name="PromotionCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="products.category",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_categories",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_categories",
                "unique_together": {("promotion", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_active", "start_date", "end_date"], name="idx_promo_active"
            ),
        ),
    ]
