# Generated by Django 4.2.10 on 2026-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("products", "Productos"),
                    ("supermarkets", "Supermercados"),
                    ("listados", "Listados de precios"),
                    ("marcas", "Marcas"),
                ],
                max_length=20,
            ),
        ),
    ]
