# Generated by Django 6.0.6 on 2026-06-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
        ("supermarkets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="nombre_lista",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="compra",
            name="supermercado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="supermarkets.supermercado",
            ),
        ),
    ]
