# Generated by Django 4.2.10 on 2026-04-27 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supermarkets", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="ARS", max_length=3)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Carga manual"),
                            ("import", "Importación CSV"),
                            ("scraping", "Scraping"),
                            ("api", "API externa"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="supermarkets.supermarketbranch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Producto",
                "verbose_name_plural": "Precios de Productos",
                "db_table": "product_prices",
                "indexes": [
                    models.Index(
                        fields=["product", "branch", "is_active"],
                        name="idx_price_lookup",
                    ),
                    models.Index(
                        fields=["product", "price"], name="idx_price_comparison"
                    ),
                ],
                "unique_together": {("product", "branch", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="ARS", max_length=3)),
                ("source", models.CharField(max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="supermarkets.supermarketbranch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Precios",
                "db_table": "price_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "branch", "created_at"],
                        name="idx_price_history",
                    )
                ],
            },
        ),
    ]
