# Generated by Django 4.2.10 on 2026-04-27 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supermarkets", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("completed", "Completada"),
                            ("archived", "Archivada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "preferred_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_lists",
                        to="supermarkets.supermarketbranch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Compra",
                "verbose_name_plural": "Listas de Compra",
                "db_table": "shopping_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListEstimation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_estimated",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("items_with_price", models.PositiveSmallIntegerField(default=0)),
                ("items_without_price", models.PositiveSmallIntegerField(default=0)),
                ("currency", models.CharField(default="ARS", max_length=3)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_estimations",
                        to="supermarkets.supermarketbranch",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimations",
                        to="shopping_lists.shoppinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estimación de Lista",
                "db_table": "shopping_list_estimations",
                "ordering": ["total_estimated"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("is_purchased", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_list_items",
                        to="products.product",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping_lists.shoppinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Lista",
                "db_table": "shopping_list_items",
                "unique_together": {("shopping_list", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(fields=["user", "status"], name="idx_list_user_status"),
        ),
    ]
