# Generated by Django 4.2.10 on 2026-04-27 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupermarketChain",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="supermarkets/logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Cadena de Supermercado",
                "verbose_name_plural": "Cadenas de Supermercado",
                "db_table": "supermarket_chains",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupermarketBranch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, db_index=True, max_length=50)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("province", models.CharField(db_index=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="supermarkets.supermarketchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "supermarket_branches",
            },
        ),
        migrations.CreateModel(
            name="BranchOpeningHours",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="supermarkets.supermarketbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Sucursal",
                "db_table": "branch_opening_hours",
            },
        ),
        migrations.AddIndex(
            model_name="supermarketbranch",
            index=models.Index(fields=["city", "province"], name="idx_branch_location"),
        ),
        migrations.AddIndex(
            model_name="supermarketbranch",
            index=models.Index(fields=["latitude", "longitude"], name="idx_branch_geo"),
        ),
        migrations.AlterUniqueTogether(
            name="branchopeninghours",
            unique_together={("branch", "weekday")},
        ),
    ]
