# Generated by Django 4.2.10 on 2026-06-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supermercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=500)),
                ("latitud", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitud", models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                "verbose_name": "Supermercado",
                "verbose_name_plural": "Supermercados",
                "db_table": "supermercado",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProductoListado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listados",
                        to="products.producto",
                    ),
                ),
                (
                    "supermercado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listados",
                        to="supermarkets.supermercado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Listado",
                "verbose_name_plural": "Productos Listados",
                "db_table": "producto_listado",
                "unique_together": {("producto", "supermercado")},
            },
        ),
    ]
